### ISSUE TITLE
AttributeError: 'COCODataset' object has no attribute 'dataset'

### ISSUE THREAD

**Issue by 7eta** [Okery/PyTorch-Simple-MaskRCNN#14]
I converted `eval.ipynb` to `eval.py` using` ipynb-py-convert` then, i ran `eval.py`
and show me the error message.
how to solve it?

```
device: cpu
loading annotations into memory...
Done (t=7.00s)
creating index...
index created!
Namespace(ckpt_path='./ckpt/maskrcnn_coco.pth', data_dir='./data/coco2017', dataset='coco', iters=-1, results='./ckpt\\results.pth', use_cuda=True)
python-BaseException
Traceback (most recent call last):
  File "C:\JetBrains\PyCharm Community Edition 2020.3.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\JetBrains\PyCharm Community Edition 2020.3.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/user/Desktop/PyTorch-Simple-MaskRCNN/eval.py", line 48, in <module>
    main(args)
  File "C:/Users/user/Desktop/PyTorch-Simple-MaskRCNN/eval.py", line 17, in main
    num_classes = len(d_test.dataset.classes) + 1
AttributeError: 'COCODataset' object has no attribute 'dataset'
```

**Comment by hamidrezarahimi** [comment]
Use `len(d_test.classes) + 1` instead of `len(d_test.dataset.classes) + 1`
