### ISSUE TITLE
Error: No such file or directory: '/data/coco2017/annotations/instances_val2017.json'

### ISSUE THREAD

**Issue by WWaynee** [Okery/PyTorch-Simple-MaskRCNN#5]
D:\Anaconda3\envs\pytorch\python.exe C:/Users/12426/PyTorch-Simple-MaskRCNN/train.py

device: cpu
Namespace(ckpt_path='./maskrcnn_coco.pth', data_dir='/data/coco2017', dataset='coco', epochs=1, iters=200, lr=0.00125, lr_steps=[22, 26], momentum=0.9, print_freq=100, results='.\\results.pth', seed=3, use_cuda=False, weight_decay=0.0001)
loading annotations into memory...
Traceback (most recent call last):
  File "C:/Users/12426/PyTorch-Simple-MaskRCNN/train.py", line 120, in <module>
    main(args)
  File "C:/Users/12426/PyTorch-Simple-MaskRCNN/train.py", line 24, in main
Done (t=0.04s)
creating index...
index created!
loading annotations into memory...
    d_test = pmr.datasets(args.dataset, args.data_dir, "val2017", train=True) # set train2017=True for eval
  File "C:\Users\12426\PyTorch-Simple-MaskRCNN\pytorch_mask_rcnn\datasets\utils.py", line 13, in datasets
    return COCODataset(*args, **kwargs)
  File "C:\Users\12426\PyTorch-Simple-MaskRCNN\pytorch_mask_rcnn\datasets\coco_dataset.py", line 19, in __init__
    self.coco = COCO(ann_file)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\pycocotools\coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '/data/coco2017/annotations/instances_val2017.json'

**Comment by PL-96** [comment]
you may give a absolute path

**Comment by WWaynee** [comment]
> you may give an absolute path

Yeah I found that the json files' content included something strange, the path of image file should have been a relative path, but after labelling images the path in json file is like "/xxxx/xxxx/1.jpg", just delete the prefix of the path and it works.
