### ISSUE TITLE
Error:Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by WWaynee** [Okery/PyTorch-Simple-MaskRCNN#6]
I only have CPU device and the error occurred:

Traceback (most recent call last):
  File "C:/Users/12426/PyTorch-Simple-MaskRCNN/train.py", line 119, in <module>
    main(args)
  File "C:/Users/12426/PyTorch-Simple-MaskRCNN/train.py", line 64, in main
    eval_output, iter_eval = pmr.evaluate(model, d_test, device, args)
  File "C:\Users\12426\PyTorch-Simple-MaskRCNN\pytorch_mask_rcnn\engine.py", line 59, in evaluate
    iter_eval = generate_results(model, data_loader, device, args)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\autograd\grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\12426\PyTorch-Simple-MaskRCNN\pytorch_mask_rcnn\engine.py", line 101, in generate_results
    torch.cuda.synchronize()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\cuda\__init__.py", line 396, in synchronize
    _lazy_init()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\cuda\__init__.py", line 186, in _lazy_init
    _check_driver()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\cuda\__init__.py", line 61, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by Okery** [comment]
The training part of code actually doesn't support CPU. I don't recommend you to train the model with CPU. It's really SLOW!
